In [1]:
import numpy as np

### 1. Write a Python Program to Add Two Matrices?

**Ans:**

In [2]:
mat1 = np.mat(([1,2], [3,4]))
mat2 = np.mat(([5,6], [7,8]))

mat1 + mat2

matrix([[ 6,  8],
        [10, 12]])

### 2. Write a Python Program to Multiply Two Matrices?

**Ans:**

In [3]:
mat1 = np.mat(([1,2], [3,4]))
mat2 = np.mat(([5,6], [7,8]))

mat1 * mat2

matrix([[19, 22],
        [43, 50]])

### 3. Write a Python Program to Transpose a Matrix?

**Ans:**

In [4]:
mat = np.mat(([1,2], [3,4]))
print(mat)
print("\nTranspose")
print(mat.T)

[[1 2]
 [3 4]]

Transpose
[[1 3]
 [2 4]]


### 4. Write a Python Program to Sort Words in Alphabetic Order?

**Ans:**

In [5]:
string = "hello world. this is a text"

words = string.split()

words.sort()

for word in words:
    print(word)

a
hello
is
text
this
world.


### 5. Write a Python Program to Remove Punctuation From a String?

**Ans:**

In [6]:
import re

string = "Hello, world : for ! Python ;"
newtext = re.sub(r'[^A-Za-z]+', ' ', string)
newtext

'Hello world for Python '