In [1]:
import numpy as np

### 1. Write a Python Program to find sum of array?

**Ans:**

In [2]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)
np.sum(arr)

[[1 2 3]
 [4 5 6]]


21

### 2. Write a Python Program to find largest element in an array?

**Ans:**

In [3]:
arr = np.array(([1,2,3],[4,5,6]))
print(arr)
np.max(arr)

[[1 2 3]
 [4 5 6]]


6

### 3. Write a Python Program for array rotation?

**Ans:**

In [4]:
arr = np.array([[1,2], [3,4], [5,6]])
np.rot90(arr)

array([[2, 4, 6],
       [1, 3, 5]])

### 4. Write a Python Program to Split the array and add the first part to the end?

**Ans:**

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)
newarr.append(newarr[0])
newarr.pop(0)

arr = np.concatenate((newarr[0], newarr[1], newarr[2]))
arr

array([3, 4, 5, 6, 1, 2])

### 5.Write a Python Program to check if given array is Monotonic?

**Ans:**

In [6]:
arr = [6, 5, 4, 4]

all(arr[i] <= arr[i + 1] for i in range(len(arr) - 1)) or all(arr[i] >= arr[i + 1] for i in range(len(arr) - 1))

True